import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { Toaster } from 'sonner';

const leagueSpartan = localFont({
  src: '../../public/fonts/League_Spartan/LeagueSpartan-VariableFont_wght.ttf',
  variable: '--font-leagueSpartan-base',
  display: 'swap',
  weight: '200 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='scroll-smooth'
    >
      <body className={`${leagueSpartan.variable} antialiased`}>
        {children}
        <Toaster
          position='top-right'
          richColors
        />
      </body>
    </html>
  );
}
